name: Release Extension

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: 'v2.0.0'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build extension
      run: npm run build
      
    - name: Create extension package
      run: |
        mkdir -p dist
        cp manifest.json background.js popup.html popup.js blocked.html blocked.js README.md INSTALL.md LICENSE dist/
        cp -r icons dist/
        cd dist
        zip -r ../palestinian-domain-blocker-extension.zip .
        cd ..
        
    - name: Get version from manifest
      id: version
      run: |
        VERSION=$(node -p "require('./manifest.json').version")
        echo "version=v$VERSION" >> $GITHUB_OUTPUT
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version.outputs.version }}
        release_name: Palestinian Domain Blocker ${{ steps.version.outputs.version }}
        body: |
          ## Palestinian Domain Blocker Extension Release
          
          ### Installation Instructions
          
          1. Download the `palestinian-domain-blocker-extension.zip` file below
          2. Extract the zip file to a folder
          3. Open Chrome/Edge/Brave and go to Extensions page
          4. Enable "Developer mode"
          5. Click "Load unpacked" and select the extracted folder
          6. The extension is now installed and ready to use!
          
          ### Features
          - Block 250+ Israeli domains and companies
          - Community-driven domain submission
          - Real-time blocking with Chrome's declarativeNetRequest API
          - Personal impact tracking
          - Alternative service recommendations
          - Palestinian-themed UI with Arabic text support
          
          ### Support
          - Report issues: [GitHub Issues](https://github.com/arcanstone/Palestinian-Domain-Blocker-v2/issues)
          - Submit new domains: Use the extension's built-in submission feature
          
          Built with ❤️ for Palestinian solidarity
        draft: false
        prerelease: false
        
    - name: Upload Extension Package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./palestinian-domain-blocker-extension.zip
        asset_name: palestinian-domain-blocker-extension.zip
        asset_content_type: application/zip
        
    - name: Upload Installation Guide
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./INSTALL.md
        asset_name: INSTALL.md
        asset_content_type: text/markdown